package com.axiell.ehub;

public enum ErrorCauseArgumentType {
    BORROWER_LIMIT_REACHED, INACTIVE_LOAN, LIBRARY_LIMIT_REACHED, MAX_NO_OF_DOWNLOADS_FOR_PRODUCT_REACHED, MISSING_CONTENT_IN_LOAN,
    PRODUCT_INACTIVE, PRODUCT_UNAVAILABLE, INVALID_CONTENT_PROVIDER_RECORD_ID, INVALID_REGION_ID, INVALID_FORMAT_ID, CREATE_LOAN_FAILED, INVALID_LOAN_ID,
    CHECKOUT_NOT_FOUND, ALREADY_ON_LOAN, INVALID_PATRON, ANOTHER_FORMAT_LOCKED_IN
}
