drop table CONTENT_PROVIDER cascade constraints;
drop table CONTENT_PROVIDER_CONSUMER cascade constraints;
drop table CONTENT_PROVIDER_PROPERTY cascade constraints;
drop table CONTENT_P_CONSUMER_PROPERTY cascade constraints;
drop table CONTENT_P_FORMAT_DECORATION cascade constraints;
drop table CONTENT_P_FORMAT_LANGUAGE cascade constraints;
drop table CONTENT_P_FORMAT_TEXT_BUNDLE cascade constraints;
drop table EHUB_ADMIN_USER cascade constraints;
drop table EHUB_CONSUMER cascade constraints;
drop table EHUB_CONSUMER_PROPERTY cascade constraints;
drop table EHUB_LOAN cascade constraints;
drop table CONTENT_PROVIDER_NAME cascade constraints;
drop table CONTENT_DISPOSITION cascade constraints;
drop table EHUB_CONSUMER_PROPERTY_KEY cascade constraints;
drop table CONTENT_P_CONSUMER_P_KEY cascade constraints;
drop table CONTENT_PROVIDER_PROPERTY_KEY cascade constraints;
drop sequence hibernate_sequence;
