spool upgrade-0.7-0.8.log
set define off

PROMPT insert-into-release.sql
@@../../basic/insert-into-release.sql

WHENEVER SQLERROR EXIT FAILURE

rem drop table content_provider_name cascade constraints;

rem ALTER TABLE CONTENT_PROVIDER_CONSUMER MODIFY (
 rem CONTENT_PROVIDER_ID NOT NULL,
 rem EHUB_CONSUMER_ID NOT NULL);

rem alter table CONTENT_P_FORMAT_LANGUAGE
rem rename to language;

rem alter table language rename column language to id;

rem ALTER TABLE CONTENT_P_FORMAT_TEXT_BUNDLE  rename column LANGUAGE to language_id;
rem ALTER TABLE CONTENT_P_FORMAT_TEXT_BUNDLE DROP CONSTRAINT FK_CONT_P_F_T_B_CONT_P_F_L;
ALTER TABLE CONTENT_P_FORMAT_TEXT_BUNDLE DROP CONSTRAINT UK_CONTENT_P_FORMAT_TEXT_BUNDL;
ALTER TABLE CONTENT_P_FORMAT_TEXT_BUNDLE ADD CONSTRAINT FK_CONTENT_P_F_T_B_LANGUAGE FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE(ID);
ALTER TABLE CONTENT_P_FORMAT_TEXT_BUNDLE ADD CONSTRAINT UK_CONTENT_P_FORMAT_TEXT_BUNDL UNIQUE (CONTENT_P_FORMAT_DECORATION_ID,LANGUAGE_ID);

ALTER TABLE EHUB_CONSUMER ADD (DEFAULT_LANGUAGE_ID VARCHAR2(255 CHAR));
update ehub_consumer set default_language_id='sv';
commit;
ALTER TABLE EHUB_CONSUMER MODIFY (default_language_id not null);
ALTER TABLE EHUB_CONSUMER ADD CONSTRAINT FK_EHUB_CONSUMER_LANGUAGE FOREIGN KEY (DEFAULT_LANGUAGE_ID) REFERENCES LANGUAGE(ID);

CREATE TABLE ERROR_CAUSE_ARGUMENT_VALUE(
  ID NUMBER NOT NULL,
  CREATE_DATETIME TIMESTAMP NOT NULL,
  MODIFY_DATETIME TIMESTAMP NOT NULL,
  TYPE VARCHAR2(255 CHAR),
  CONSTRAINT PK_ERROR_CAUSE_ARGUMENT_VALUE PRIMARY KEY (ID) ENABLE,
  CONSTRAINT UK_ERROR_CAUSE_ARGUMENT_VALUE UNIQUE (TYPE) ENABLE
);

CREATE TABLE ERROR_C_A_V_TEXT_BUNDLE(
  ID NUMBER NOT NULL,
  ERROR_CAUSE_ARGUMENT_VALUE_ID NUMBER NOT NULL,
  TEXT VARCHAR2(255 CHAR),
  LANGUAGE_ID VARCHAR2(255 CHAR) NOT NULL,
  CREATE_DATETIME TIMESTAMP NOT NULL,
  MODIFY_DATETIME TIMESTAMP NOT NULL,
  CONSTRAINT PK_ERROR_C_A_V_TEXT_BUNDLE PRIMARY KEY (ERROR_CAUSE_ARGUMENT_VALUE_ID,LANGUAGE_ID) ENABLE,
  CONSTRAINT FK_ERROR_C_A_V_T_B_LANGUAGE FOREIGN KEY ("LANGUAGE_ID") REFERENCES LANGUAGE (ID),
  CONSTRAINT FK_ERROR_C_A_V_T_B_ERROR_C_A_V FOREIGN KEY (ERROR_CAUSE_ARGUMENT_VALUE_ID)
  REFERENCES ERROR_CAUSE_ARGUMENT_VALUE(ID)
);

insert into ERROR_CAUSE_ARGUMENT_VALUE (id, type, CREATE_DATETIME,MODIFY_DATETIME) VALUES (1,'BORROWER_LIMIT_REACHED', systimestamp, systimestamp);
insert into ERROR_CAUSE_ARGUMENT_VALUE (id, type, CREATE_DATETIME,MODIFY_DATETIME) VALUES (2,'INACTIVE_LOAN', systimestamp, systimestamp);
insert into ERROR_CAUSE_ARGUMENT_VALUE (id, type, CREATE_DATETIME,MODIFY_DATETIME) VALUES (3,'LIBRARY_LIMIT_REACHED', systimestamp, systimestamp);
insert into ERROR_CAUSE_ARGUMENT_VALUE (id, type, CREATE_DATETIME,MODIFY_DATETIME) VALUES (4,'MAX_NO_OF_DOWNLOADS_FOR_PRODUCT_REACHED', systimestamp, systimestamp);
insert into ERROR_CAUSE_ARGUMENT_VALUE (id, type, CREATE_DATETIME,MODIFY_DATETIME) VALUES (5,'MISSING_CONTENT_IN_LOAN', systimestamp, systimestamp);
insert into ERROR_CAUSE_ARGUMENT_VALUE (id, type, CREATE_DATETIME,MODIFY_DATETIME) VALUES (6,'PRODUCT_INACTIVE', systimestamp, systimestamp);
insert into ERROR_CAUSE_ARGUMENT_VALUE (id, type, CREATE_DATETIME,MODIFY_DATETIME) VALUES (7,'PRODUCT_UNAVAILABLE', systimestamp, systimestamp);

insert into CONTENT_PROVIDER(id, NAME, CREATE_DATETIME, MODIFY_DATETIME) VALUES(6, 'ELIB3', systimestamp, systimestamp);

commit;

PROMPT rename-constraints.sql
@@../../basic/rename-constraints.sql

PROMPT create-fk-indexes.sql
@@../../basic/create-fk-indexes.sql

spool off