debug: true

spring:
  mvc:
    log-request-details: true

logging:
  level:
    root: WARN
    com.axiell: INFO
    org.apache.cxf: WARN
    org.apache.wicket: WARN
    io.swagger: WARN
    org.springframework.web: WARN
