server:
  port: ${SERVICE_PORT:16518}
  servlet:
    encoding:
      charset: UTF-8
      force: true

info:
  component: "@project.name@"        #getting controller name
  description: "@project.description@" #getting controller description
  version: "@project.version@"        #getting the controller version

spring:
  application:
    name: ehub

  main:
    banner-mode: "off"

  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;sql.enforce_strict_size=true;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

cxf:
  path: /api
  jaxrs:
    classes-scan-packages: com.axiell.ehub.controller.external

    client:
      address: http://localhost:16518/api
      classes-scan-packages: com.axiell.ehub.controller.external
      headers:
        accept: application/json

logging:
  level:
    root: WARN

  config: classpath:log4j2-default.xml
  file:
    path: ${LOG_PATH:logs}

management:
  endpoints:
    web:
      exposure:
        include: '*'

