debug: true

spring:
  mvc:
    log-request-details: true

logging:
  level:
    root: WARN
    com.axiell: DEBUG
    org.apache.cxf: INFO
    org.apache.wicket: DEBUG
    io.swagger: WARN
    org.springframework.web: WARN
