WHENEVER SQLERROR EXIT FAILURE

insert into EHUB_CONSUMER (id, SECRET_KEY, DESCRIPTION, DEFAULT_LANGUAGE_ID, CREATE_DATETIME, MODIFY_DATETIME) values (1, 'secret1', 'Axiell Ehub Consumer', 'en', systimestamp, systimestamp);

insert into EHUB_CONSUMER_PROPERTY (EHUB_CONSUMER_ID, PROPERTY_KEY, PROPERTY_VALUE) values (1, 'ARENA_PALMA_URL', 'http://localhost:16521/arena.pa.palma');
insert into EHUB_CONSUMER_PROPERTY (EHUB_CONSUMER_ID, PROPERTY_KEY, PROPERTY_VALUE) values (1, 'ARENA_AGENCY_M_IDENTIFIER', 'MSE000001');

insert into CONTENT_PROVIDER_CONSUMER (id, CONTENT_PROVIDER_ID, EHUB_CONSUMER_ID, CREATE_DATETIME, MODIFY_DATETIME) values (1, 1, 1, systimestamp,systimestamp);

insert into CONTENT_P_CONSUMER_PROPERTY (CONTENT_PROVIDER_CONSUMER_ID, PROPERTY_KEY, PROPERTY_VALUE) values (1, 'ELIB_RETAILER_ID', '926');
insert into CONTENT_P_CONSUMER_PROPERTY (CONTENT_PROVIDER_CONSUMER_ID, PROPERTY_KEY, PROPERTY_VALUE) values (1, 'ELIB_RETAILER_KEY', 'hu81K8js');

insert into CONTENT_PROVIDER_CONSUMER (id, CONTENT_PROVIDER_ID, EHUB_CONSUMER_ID, CREATE_DATETIME, MODIFY_DATETIME) values (2, 2, 1, systimestamp, systimestamp);

insert into CONTENT_P_CONSUMER_PROPERTY (CONTENT_PROVIDER_CONSUMER_ID, PROPERTY_KEY, PROPERTY_VALUE) values (2, 'ELIBU_SERVICE_ID', '934');
insert into CONTENT_P_CONSUMER_PROPERTY (CONTENT_PROVIDER_CONSUMER_ID, PROPERTY_KEY, PROPERTY_VALUE) values (2, 'ELIBU_SERVICE_KEY', 'xvfKOWHNeZF3');
insert into CONTENT_P_CONSUMER_PROPERTY (CONTENT_PROVIDER_CONSUMER_ID, PROPERTY_KEY, PROPERTY_VALUE) values (2, 'SUBSCRIPTION_ID', '3');

insert into EHUB_LOAN(id, EHUB_CONSUMER_ID, CONTENT_PROVIDER_ID, CONTENT_P_FORMAT_DECORATION_ID, CONTENT_PROVIDER_LOAN_ID, LMS_LOAN_ID, EXPIRATION_DATE, CREATE_DATETIME, MODIFY_DATETIME) values (1, 1, 1, 2, 'contentProviderLoanId', 'lmsLoanId', systimestamp, systimestamp, systimestamp);

commit;

