<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="eBookService" targetNamespace="http://tempuri.org/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
	xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy"
	xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract"
	xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:tns="http://tempuri.org/" xmlns:wsa10="http://www.w3.org/2005/08/addressing"
	xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing">
	<wsdl:types>
		<xs:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/"
			xmlns:xs="http://www.w3.org/2001/XMLSchema">
			<xs:import namespace="http://schemas.datacontract.org/2004/07/AHES" />
			<xs:element name="AuthenticateUser">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="Barcode" nillable="true"
							type="xs:string" />
						<xs:element minOccurs="0" name="Pin" nillable="true"
							type="xs:string" />
						<xs:element minOccurs="0" name="Authid" type="xs:int" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="AuthenticateUserResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="AuthenticateUserResult"
							nillable="true" type="q1:UserDetailsBasic"
							xmlns:q1="http://schemas.datacontract.org/2004/07/AHES" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="SearchCatalog">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="SearchText" nillable="true"
							type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="SearchCatalogResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="SearchCatalogResult"
							nillable="true" type="q2:BibResults"
							xmlns:q2="http://schemas.datacontract.org/2004/07/AHES" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="SearchCatalogA">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="SearchText" nillable="true"
							type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="SearchCatalogAResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="SearchCatalogAResult"
							nillable="true" type="q3:BibResultsA"
							xmlns:q3="http://schemas.datacontract.org/2004/07/AHES" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getBooks">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="SearchText" nillable="true"
							type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getBooksResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="getBooksResult"
							nillable="true" type="q4:ArrayOfclsBooks"
							xmlns:q4="http://schemas.datacontract.org/2004/07/AHES" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getSearchResults">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="UserID" type="xs:int" />
						<xs:element minOccurs="0" name="AuthID" type="xs:int" />
						<xs:element minOccurs="0" name="SearchText" nillable="true"
							type="xs:string" />
						<xs:element minOccurs="0" name="InStock" type="xs:int" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getSearchResultsResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="getSearchResultsResult"
							nillable="true" type="q5:ArrayOfBibSearchResults"
							xmlns:q5="http://schemas.datacontract.org/2004/07/AHES" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getLoanDetails">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="UserID" type="xs:int" />
						<xs:element minOccurs="0" name="AuthID" type="xs:int" />
						<xs:element minOccurs="0" name="LoanType" type="xs:int" />
						<xs:element minOccurs="0" name="LoanID" type="xs:int" />
						<xs:element minOccurs="0" name="TokenKey" nillable="true"
							type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getLoanDetailsResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="getLoanDetailsResult"
							nillable="true" type="q6:ArrayOfLoanDetails"
							xmlns:q6="http://schemas.datacontract.org/2004/07/AHES" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getUserID">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="Barcode" nillable="true"
							type="xs:string" />
						<xs:element minOccurs="0" name="AuthID" type="xs:int" />
						<xs:element minOccurs="0" name="TokenKey" nillable="true"
							type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getUserIDResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="getUserIDResult"
							nillable="true" type="q7:UserLookupResult"
							xmlns:q7="http://schemas.datacontract.org/2004/07/AHES" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getBookBib">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="UserID" type="xs:int" />
						<xs:element minOccurs="0" name="AuthID" type="xs:int" />
						<xs:element minOccurs="0" name="EAN" nillable="true"
							type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getBookBibResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="getBookBibResult"
							nillable="true" type="q8:BibTitle"
							xmlns:q8="http://schemas.datacontract.org/2004/07/AHES" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ManageBasketItem">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="UserID" type="xs:int" />
						<xs:element minOccurs="0" name="AuthID" type="xs:int" />
						<xs:element minOccurs="0" name="EAN" nillable="true"
							type="xs:string" />
						<xs:element minOccurs="0" name="ActionType" type="xs:int" />
						<xs:element minOccurs="0" name="TokenKey" nillable="true"
							type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ManageBasketItemResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="ManageBasketItemResult"
							nillable="true" type="q9:BasketItemActionResult"
							xmlns:q9="http://schemas.datacontract.org/2004/07/AHES" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ManageLoanRequest">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="UserID" type="xs:int" />
						<xs:element minOccurs="0" name="AuthID" type="xs:int" />
						<xs:element minOccurs="0" name="EAN" nillable="true"
							type="xs:string" />
						<xs:element minOccurs="0" name="Duration" type="xs:int" />
						<xs:element minOccurs="0" name="TokenKey" nillable="true"
							type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ManageLoanRequestResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="ManageLoanRequestResult"
							nillable="true" type="q10:LoanRequestResult"
							xmlns:q10="http://schemas.datacontract.org/2004/07/AHES" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getBasketContents">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="UserID" type="xs:int" />
						<xs:element minOccurs="0" name="AuthID" type="xs:int" />
						<xs:element minOccurs="0" name="EAN" nillable="true"
							type="xs:string" />
						<xs:element minOccurs="0" name="TokenKey" nillable="true"
							type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getBasketContentsResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="getBasketContentsResult"
							nillable="true" type="q11:ArrayOfBasketContentsResult"
							xmlns:q11="http://schemas.datacontract.org/2004/07/AHES" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getTitleAvailabilty">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="UserID" type="xs:int" />
						<xs:element minOccurs="0" name="AuthID" type="xs:int" />
						<xs:element minOccurs="0" name="EAN" nillable="true"
							type="xs:string" />
						<xs:element minOccurs="0" name="TokenKey" nillable="true"
							type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getTitleAvailabiltyResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="getTitleAvailabiltyResult"
							nillable="true" type="q12:ArrayOftitle"
							xmlns:q12="http://schemas.datacontract.org/2004/07/AHES" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ProcessLoan">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="UserID" type="xs:int" />
						<xs:element minOccurs="0" name="AuthID" type="xs:int" />
						<xs:element minOccurs="0" name="EAN" nillable="true"
							type="xs:string" />
						<xs:element minOccurs="0" name="Duration" type="xs:int" />
						<xs:element minOccurs="0" name="TokenKey" nillable="true"
							type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ProcessLoanResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="0" name="ProcessLoanResult"
							nillable="true" type="q13:LoanRequestResult"
							xmlns:q13="http://schemas.datacontract.org/2004/07/AHES" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:schema>
		<xs:schema attributeFormDefault="qualified"
			elementFormDefault="qualified"
			targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/"
			xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/">
			<xs:element name="anyType" nillable="true" type="xs:anyType" />
			<xs:element name="anyURI" nillable="true" type="xs:anyURI" />
			<xs:element name="base64Binary" nillable="true" type="xs:base64Binary" />
			<xs:element name="boolean" nillable="true" type="xs:boolean" />
			<xs:element name="byte" nillable="true" type="xs:byte" />
			<xs:element name="dateTime" nillable="true" type="xs:dateTime" />
			<xs:element name="decimal" nillable="true" type="xs:decimal" />
			<xs:element name="double" nillable="true" type="xs:double" />
			<xs:element name="float" nillable="true" type="xs:float" />
			<xs:element name="int" nillable="true" type="xs:int" />
			<xs:element name="long" nillable="true" type="xs:long" />
			<xs:element name="QName" nillable="true" type="xs:QName" />
			<xs:element name="short" nillable="true" type="xs:short" />
			<xs:element name="string" nillable="true" type="xs:string" />
			<xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte" />
			<xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt" />
			<xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong" />
			<xs:element name="unsignedShort" nillable="true"
				type="xs:unsignedShort" />
			<xs:element name="char" nillable="true" type="tns:char" />
			<xs:simpleType name="char">
				<xs:restriction base="xs:int" />
			</xs:simpleType>
			<xs:element name="duration" nillable="true" type="tns:duration" />
			<xs:simpleType name="duration">
				<xs:restriction base="xs:duration">
					<xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?" />
					<xs:minInclusive value="-P10675199DT2H48M5.4775808S" />
					<xs:maxInclusive value="P10675199DT2H48M5.4775807S" />
				</xs:restriction>
			</xs:simpleType>
			<xs:element name="guid" nillable="true" type="tns:guid" />
			<xs:simpleType name="guid">
				<xs:restriction base="xs:string">
					<xs:pattern
						value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}" />
				</xs:restriction>
			</xs:simpleType>
			<xs:attribute name="FactoryType" type="xs:QName" />
			<xs:attribute name="Id" type="xs:ID" />
			<xs:attribute name="Ref" type="xs:IDREF" />
		</xs:schema>
		<xs:schema elementFormDefault="qualified"
			targetNamespace="http://schemas.datacontract.org/2004/07/AHES"
			xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.datacontract.org/2004/07/AHES">
			<xs:complexType name="UserDetailsBasic">
				<xs:sequence>
					<xs:element minOccurs="0" name="AvailCredits" type="xs:int" />
					<xs:element minOccurs="0" name="ErrMessage" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="isValid" type="xs:int" />
					<xs:element minOccurs="0" name="userId" type="xs:int" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="UserDetailsBasic" nillable="true"
				type="tns:UserDetailsBasic" />
			<xs:complexType name="BibResults">
				<xs:sequence>
					<xs:element minOccurs="0" name="StrTitle" nillable="true"
						type="xs:string" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="BibResults" nillable="true" type="tns:BibResults" />
			<xs:complexType name="BibResultsA">
				<xs:sequence>
					<xs:element minOccurs="0" name="MyTable" nillable="true">
						<xs:complexType>
							<xs:annotation>
								<xs:appinfo>
									<ActualType Name="DataTable"
										Namespace="http://schemas.datacontract.org/2004/07/System.Data"
										xmlns="http://schemas.microsoft.com/2003/10/Serialization/" />
								</xs:appinfo>
							</xs:annotation>
							<xs:sequence>
								<xs:any minOccurs="0" maxOccurs="unbounded"
									namespace="http://www.w3.org/2001/XMLSchema" processContents="lax" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:complexType>
			<xs:element name="BibResultsA" nillable="true" type="tns:BibResultsA" />
			<xs:complexType name="ArrayOfclsBooks">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="unbounded" name="clsBooks"
						nillable="true" type="tns:clsBooks" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfclsBooks" nillable="true"
				type="tns:ArrayOfclsBooks" />
			<xs:complexType name="clsBooks">
				<xs:sequence>
					<xs:element minOccurs="0" name="EAN" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="title" nillable="true"
						type="xs:string" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="clsBooks" nillable="true" type="tns:clsBooks" />
			<xs:complexType name="ArrayOfBibSearchResults">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="unbounded" name="BibSearchResults"
						nillable="true" type="tns:BibSearchResults" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfBibSearchResults" nillable="true"
				type="tns:ArrayOfBibSearchResults" />
			<xs:complexType name="BibSearchResults">
				<xs:sequence>
					<xs:element minOccurs="0" name="Author" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="AuthorForename"
						nillable="true" type="xs:string" />
					<xs:element minOccurs="0" name="AvailLicences" type="xs:int" />
					<xs:element minOccurs="0" name="EAN" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="Title" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="TotalLoans" type="xs:int" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="BibSearchResults" nillable="true"
				type="tns:BibSearchResults" />
			<xs:complexType name="ArrayOfLoanDetails">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="unbounded" name="LoanDetails"
						nillable="true" type="tns:LoanDetails" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfLoanDetails" nillable="true"
				type="tns:ArrayOfLoanDetails" />
			<xs:complexType name="LoanDetails">
				<xs:sequence>
					<xs:element minOccurs="0" name="DateBorrowed" type="xs:dateTime" />
					<xs:element minOccurs="0" name="DownloadURL" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="Duration" type="xs:int" />
					<xs:element minOccurs="0" name="DurationType" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="EAN" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="ErrorCode" type="xs:int" />
					<xs:element minOccurs="0" name="ErrorDesc" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="Expiry" type="xs:dateTime" />
					<xs:element minOccurs="0" name="HasFailed" type="xs:boolean" />
					<xs:element minOccurs="0" name="HasFailedReason"
						nillable="true" type="xs:string" />
					<xs:element minOccurs="0" name="LoanID" type="xs:int" />
					<xs:element minOccurs="0" name="LoanStatus" type="xs:int" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="LoanDetails" nillable="true" type="tns:LoanDetails" />
			<xs:complexType name="UserLookupResult">
				<xs:sequence>
					<xs:element minOccurs="0" name="Authid" type="xs:int" />
					<xs:element minOccurs="0" name="Barcode" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="ErrorCode" type="xs:int" />
					<xs:element minOccurs="0" name="ErrorDesc" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="Userid" type="xs:int" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="UserLookupResult" nillable="true"
				type="tns:UserLookupResult" />
			<xs:complexType name="BibTitle">
				<xs:sequence>
					<xs:element minOccurs="0" name="EAN" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="title" nillable="true"
						type="xs:string" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="BibTitle" nillable="true" type="tns:BibTitle" />
			<xs:complexType name="BasketItemActionResult">
				<xs:sequence>
					<xs:element minOccurs="0" name="ActionSuccess" type="xs:boolean" />
					<xs:element minOccurs="0" name="ActionType" type="xs:int" />
					<xs:element minOccurs="0" name="EAN" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="ErrorCode" type="xs:int" />
					<xs:element minOccurs="0" name="ErrorDesc" nillable="true"
						type="xs:string" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="BasketItemActionResult" nillable="true"
				type="tns:BasketItemActionResult" />
			<xs:complexType name="LoanRequestResult">
				<xs:sequence>
					<xs:element minOccurs="0" name="Authid" type="xs:int" />
					<xs:element minOccurs="0" name="EAN" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="ErrorCode" type="xs:int" />
					<xs:element minOccurs="0" name="ErrorDesc" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="LoanRequestSuccess"
						type="xs:int" />
					<xs:element minOccurs="0" name="Loanid" type="xs:int" />
					<xs:element minOccurs="0" name="Userid" type="xs:int" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="LoanRequestResult" nillable="true"
				type="tns:LoanRequestResult" />
			<xs:complexType name="ArrayOfBasketContentsResult">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="unbounded"
						name="BasketContentsResult" nillable="true" type="tns:BasketContentsResult" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfBasketContentsResult" nillable="true"
				type="tns:ArrayOfBasketContentsResult" />
			<xs:complexType name="BasketContentsResult">
				<xs:sequence>
					<xs:element minOccurs="0" name="DateAdded" type="xs:dateTime" />
					<xs:element minOccurs="0" name="DateExpire" type="xs:dateTime" />
					<xs:element minOccurs="0" name="EAN" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="ErrorCode" type="xs:int" />
					<xs:element minOccurs="0" name="ErrorDesc" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="ID" type="xs:int" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="BasketContentsResult" nillable="true"
				type="tns:BasketContentsResult" />
			<xs:complexType name="ArrayOftitle">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="unbounded" name="title"
						nillable="true" type="tns:title" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOftitle" nillable="true"
				type="tns:ArrayOftitle" />
			<xs:complexType name="title">
				<xs:sequence>
					<xs:element minOccurs="0" name="EAN" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="ErrorCode" type="xs:int" />
					<xs:element minOccurs="0" name="ErrorDesc" nillable="true"
						type="xs:string" />
					<xs:element minOccurs="0" name="availability" nillable="true"
						type="tns:availability" />
					<xs:element minOccurs="0" name="drm" nillable="true"
						type="tns:drm" />
					<xs:element minOccurs="0" name="status" nillable="true"
						type="xs:string" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="title" nillable="true" type="tns:title" />
			<xs:complexType name="availability">
				<xs:sequence>
					<xs:element minOccurs="0" name="availableCopies" type="xs:int" />
					<xs:element minOccurs="0" name="holdQueueSize" type="xs:int" />
					<xs:element minOccurs="0" name="purchasable" type="xs:boolean" />
					<xs:element minOccurs="0" name="totalCopies" type="xs:int" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="availability" nillable="true"
				type="tns:availability" />
			<xs:complexType name="drm">
				<xs:sequence>
					<xs:element minOccurs="0" name="defaultCheckout" type="xs:int" />
					<xs:element minOccurs="0" name="maxCheckout" type="xs:int" />
					<xs:element minOccurs="0" name="minCheckout" type="xs:int" />
					<xs:element minOccurs="0" name="restricted" type="xs:boolean" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="drm" nillable="true" type="tns:drm" />
		</xs:schema>
		<xs:schema elementFormDefault="qualified"
			targetNamespace="http://schemas.datacontract.org/2004/07/System.Data"
			xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.datacontract.org/2004/07/System.Data">
			<xs:element name="DataTable" nillable="true">
				<xs:complexType>
					<xs:annotation>
						<xs:appinfo>
							<ActualType Name="DataTable"
								Namespace="http://schemas.datacontract.org/2004/07/System.Data"
								xmlns="http://schemas.microsoft.com/2003/10/Serialization/" />
						</xs:appinfo>
					</xs:annotation>
					<xs:sequence>
						<xs:any minOccurs="0" maxOccurs="unbounded"
							namespace="http://www.w3.org/2001/XMLSchema" processContents="lax" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="IeBookService_AuthenticateUser_InputMessage">
		<wsdl:part name="parameters" element="tns:AuthenticateUser" />
	</wsdl:message>
	<wsdl:message name="IeBookService_AuthenticateUser_OutputMessage">
		<wsdl:part name="parameters" element="tns:AuthenticateUserResponse" />
	</wsdl:message>
	<wsdl:message name="IeBookService_SearchCatalog_InputMessage">
		<wsdl:part name="parameters" element="tns:SearchCatalog" />
	</wsdl:message>
	<wsdl:message name="IeBookService_SearchCatalog_OutputMessage">
		<wsdl:part name="parameters" element="tns:SearchCatalogResponse" />
	</wsdl:message>
	<wsdl:message name="IeBookService_SearchCatalogA_InputMessage">
		<wsdl:part name="parameters" element="tns:SearchCatalogA" />
	</wsdl:message>
	<wsdl:message name="IeBookService_SearchCatalogA_OutputMessage">
		<wsdl:part name="parameters" element="tns:SearchCatalogAResponse" />
	</wsdl:message>
	<wsdl:message name="IeBookService_getBooks_InputMessage">
		<wsdl:part name="parameters" element="tns:getBooks" />
	</wsdl:message>
	<wsdl:message name="IeBookService_getBooks_OutputMessage">
		<wsdl:part name="parameters" element="tns:getBooksResponse" />
	</wsdl:message>
	<wsdl:message name="IeBookService_getSearchResults_InputMessage">
		<wsdl:part name="parameters" element="tns:getSearchResults" />
	</wsdl:message>
	<wsdl:message name="IeBookService_getSearchResults_OutputMessage">
		<wsdl:part name="parameters" element="tns:getSearchResultsResponse" />
	</wsdl:message>
	<wsdl:message name="IeBookService_getLoanDetails_InputMessage">
		<wsdl:part name="parameters" element="tns:getLoanDetails" />
	</wsdl:message>
	<wsdl:message name="IeBookService_getLoanDetails_OutputMessage">
		<wsdl:part name="parameters" element="tns:getLoanDetailsResponse" />
	</wsdl:message>
	<wsdl:message name="IeBookService_getUserID_InputMessage">
		<wsdl:part name="parameters" element="tns:getUserID" />
	</wsdl:message>
	<wsdl:message name="IeBookService_getUserID_OutputMessage">
		<wsdl:part name="parameters" element="tns:getUserIDResponse" />
	</wsdl:message>
	<wsdl:message name="IeBookService_getBookBib_InputMessage">
		<wsdl:part name="parameters" element="tns:getBookBib" />
	</wsdl:message>
	<wsdl:message name="IeBookService_getBookBib_OutputMessage">
		<wsdl:part name="parameters" element="tns:getBookBibResponse" />
	</wsdl:message>
	<wsdl:message name="IeBookService_ManageBasketItem_InputMessage">
		<wsdl:part name="parameters" element="tns:ManageBasketItem" />
	</wsdl:message>
	<wsdl:message name="IeBookService_ManageBasketItem_OutputMessage">
		<wsdl:part name="parameters" element="tns:ManageBasketItemResponse" />
	</wsdl:message>
	<wsdl:message name="IeBookService_ManageLoanRequest_InputMessage">
		<wsdl:part name="parameters" element="tns:ManageLoanRequest" />
	</wsdl:message>
	<wsdl:message name="IeBookService_ManageLoanRequest_OutputMessage">
		<wsdl:part name="parameters" element="tns:ManageLoanRequestResponse" />
	</wsdl:message>
	<wsdl:message name="IeBookService_getBasketContents_InputMessage">
		<wsdl:part name="parameters" element="tns:getBasketContents" />
	</wsdl:message>
	<wsdl:message name="IeBookService_getBasketContents_OutputMessage">
		<wsdl:part name="parameters" element="tns:getBasketContentsResponse" />
	</wsdl:message>
	<wsdl:message name="IeBookService_getTitleAvailabilty_InputMessage">
		<wsdl:part name="parameters" element="tns:getTitleAvailabilty" />
	</wsdl:message>
	<wsdl:message name="IeBookService_getTitleAvailabilty_OutputMessage">
		<wsdl:part name="parameters" element="tns:getTitleAvailabiltyResponse" />
	</wsdl:message>
	<wsdl:message name="IeBookService_ProcessLoan_InputMessage">
		<wsdl:part name="parameters" element="tns:ProcessLoan" />
	</wsdl:message>
	<wsdl:message name="IeBookService_ProcessLoan_OutputMessage">
		<wsdl:part name="parameters" element="tns:ProcessLoanResponse" />
	</wsdl:message>
	<wsdl:portType name="IeBookService">
		<wsdl:operation name="AuthenticateUser">
			<wsdl:input wsaw:Action="http://tempuri.org/IeBookService/AuthenticateUser"
				message="tns:IeBookService_AuthenticateUser_InputMessage" />
			<wsdl:output
				wsaw:Action="http://tempuri.org/IeBookService/AuthenticateUserResponse"
				message="tns:IeBookService_AuthenticateUser_OutputMessage" />
		</wsdl:operation>
		<wsdl:operation name="SearchCatalog">
			<wsdl:input wsaw:Action="http://tempuri.org/IeBookService/SearchCatalog"
				message="tns:IeBookService_SearchCatalog_InputMessage" />
			<wsdl:output wsaw:Action="http://tempuri.org/IeBookService/SearchCatalogResponse"
				message="tns:IeBookService_SearchCatalog_OutputMessage" />
		</wsdl:operation>
		<wsdl:operation name="SearchCatalogA">
			<wsdl:input wsaw:Action="http://tempuri.org/IeBookService/SearchCatalogA"
				message="tns:IeBookService_SearchCatalogA_InputMessage" />
			<wsdl:output
				wsaw:Action="http://tempuri.org/IeBookService/SearchCatalogAResponse"
				message="tns:IeBookService_SearchCatalogA_OutputMessage" />
		</wsdl:operation>
		<wsdl:operation name="getBooks">
			<wsdl:input wsaw:Action="http://tempuri.org/IeBookService/getBooks"
				message="tns:IeBookService_getBooks_InputMessage" />
			<wsdl:output wsaw:Action="http://tempuri.org/IeBookService/getBooksResponse"
				message="tns:IeBookService_getBooks_OutputMessage" />
		</wsdl:operation>
		<wsdl:operation name="getSearchResults">
			<wsdl:input wsaw:Action="http://tempuri.org/IeBookService/getSearchResults"
				message="tns:IeBookService_getSearchResults_InputMessage" />
			<wsdl:output
				wsaw:Action="http://tempuri.org/IeBookService/getSearchResultsResponse"
				message="tns:IeBookService_getSearchResults_OutputMessage" />
		</wsdl:operation>
		<wsdl:operation name="getLoanDetails">
			<wsdl:input wsaw:Action="http://tempuri.org/IeBookService/getLoanDetails"
				message="tns:IeBookService_getLoanDetails_InputMessage" />
			<wsdl:output
				wsaw:Action="http://tempuri.org/IeBookService/getLoanDetailsResponse"
				message="tns:IeBookService_getLoanDetails_OutputMessage" />
		</wsdl:operation>
		<wsdl:operation name="getUserID">
			<wsdl:input wsaw:Action="http://tempuri.org/IeBookService/getUserID"
				message="tns:IeBookService_getUserID_InputMessage" />
			<wsdl:output wsaw:Action="http://tempuri.org/IeBookService/getUserIDResponse"
				message="tns:IeBookService_getUserID_OutputMessage" />
		</wsdl:operation>
		<wsdl:operation name="getBookBib">
			<wsdl:input wsaw:Action="http://tempuri.org/IeBookService/getBookBib"
				message="tns:IeBookService_getBookBib_InputMessage" />
			<wsdl:output wsaw:Action="http://tempuri.org/IeBookService/getBookBibResponse"
				message="tns:IeBookService_getBookBib_OutputMessage" />
		</wsdl:operation>
		<wsdl:operation name="ManageBasketItem">
			<wsdl:input wsaw:Action="http://tempuri.org/IeBookService/ManageBasketItem"
				message="tns:IeBookService_ManageBasketItem_InputMessage" />
			<wsdl:output
				wsaw:Action="http://tempuri.org/IeBookService/ManageBasketItemResponse"
				message="tns:IeBookService_ManageBasketItem_OutputMessage" />
		</wsdl:operation>
		<wsdl:operation name="ManageLoanRequest">
			<wsdl:input wsaw:Action="http://tempuri.org/IeBookService/ManageLoanRequest"
				message="tns:IeBookService_ManageLoanRequest_InputMessage" />
			<wsdl:output
				wsaw:Action="http://tempuri.org/IeBookService/ManageLoanRequestResponse"
				message="tns:IeBookService_ManageLoanRequest_OutputMessage" />
		</wsdl:operation>
		<wsdl:operation name="getBasketContents">
			<wsdl:input wsaw:Action="http://tempuri.org/IeBookService/getBasketContents"
				message="tns:IeBookService_getBasketContents_InputMessage" />
			<wsdl:output
				wsaw:Action="http://tempuri.org/IeBookService/getBasketContentsResponse"
				message="tns:IeBookService_getBasketContents_OutputMessage" />
		</wsdl:operation>
		<wsdl:operation name="getTitleAvailabilty">
			<wsdl:input wsaw:Action="http://tempuri.org/IeBookService/getTitleAvailabilty"
				message="tns:IeBookService_getTitleAvailabilty_InputMessage" />
			<wsdl:output
				wsaw:Action="http://tempuri.org/IeBookService/getTitleAvailabiltyResponse"
				message="tns:IeBookService_getTitleAvailabilty_OutputMessage" />
		</wsdl:operation>
		<wsdl:operation name="ProcessLoan">
			<wsdl:input wsaw:Action="http://tempuri.org/IeBookService/ProcessLoan"
				message="tns:IeBookService_ProcessLoan_InputMessage" />
			<wsdl:output wsaw:Action="http://tempuri.org/IeBookService/ProcessLoanResponse"
				message="tns:IeBookService_ProcessLoan_OutputMessage" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="BasicHttpBinding_IeBookService" type="tns:IeBookService">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="AuthenticateUser">
			<soap:operation soapAction="http://tempuri.org/IeBookService/AuthenticateUser"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="SearchCatalog">
			<soap:operation soapAction="http://tempuri.org/IeBookService/SearchCatalog"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="SearchCatalogA">
			<soap:operation soapAction="http://tempuri.org/IeBookService/SearchCatalogA"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getBooks">
			<soap:operation soapAction="http://tempuri.org/IeBookService/getBooks"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getSearchResults">
			<soap:operation soapAction="http://tempuri.org/IeBookService/getSearchResults"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getLoanDetails">
			<soap:operation soapAction="http://tempuri.org/IeBookService/getLoanDetails"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getUserID">
			<soap:operation soapAction="http://tempuri.org/IeBookService/getUserID"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getBookBib">
			<soap:operation soapAction="http://tempuri.org/IeBookService/getBookBib"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="ManageBasketItem">
			<soap:operation soapAction="http://tempuri.org/IeBookService/ManageBasketItem"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="ManageLoanRequest">
			<soap:operation soapAction="http://tempuri.org/IeBookService/ManageLoanRequest"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getBasketContents">
			<soap:operation soapAction="http://tempuri.org/IeBookService/getBasketContents"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getTitleAvailabilty">
			<soap:operation
				soapAction="http://tempuri.org/IeBookService/getTitleAvailabilty"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="ProcessLoan">
			<soap:operation soapAction="http://tempuri.org/IeBookService/ProcessLoan"
				style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="eBookService">
		<wsdl:port name="BasicHttpBinding_IeBookService" binding="tns:BasicHttpBinding_IeBookService">
			<soap:address location="http://api.libraryebooks.co.uk/AHLS/eBookService.svc" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>